language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: pMQ455/mT9pc5Fzr+hlb96HoqTFvjz6dSdNP/gvhaY/eqQnzQ6ygjE5VsrzqDmYLrJgssq20c4Vnr2XdVssfgy2MaxvzUEykn//neBmXiN7JMa08HXa4YOqZbElH1s12s+UKXE47su4J3FS86aap8F04s6NJtCtzWIuj1/9pB6JHEr3a5PUf+vXC4jlPf+bUcanSaUEHKoxf48836hS5u2e11wTXDq5/wix/nw0O52dawSFxVGgZqdnYILlCKgMeFJRmyQVbVXRAa2mefS7Jia0f2A9eJpYCdL1lQOUB7IUcWkRhyeku3r/HKQmejxQ+JZrCHcmnP629+2kzamB9XPZZ5OSRmbMYfAREDUWgQ28+eh4MN+xkUDuAQIu059mtfSVEKkSuclU8yt8RLVfb46UD0DK3ayYfdfRz7usLTqy35XFjLlFxia1ijZlDbs/c+GN/i/+FL4ROeeqdnRwj67NUDM5hoMLOS/Yodna1JCMR3SlUVDRUvbnRGwZtGIG4O8AKOabiw7PS++zElMtLfdmgdnfnlB9ro1cEfx69xeXzTZQB4298CLqgMj5fu9+v4wpc1fOxdHZIWfhqUkZp9+ozf3xVv8CXMmw9CUTYjqF45aLVyOhrfRFacVu3t8m/W3U4U6S77u4J7llRGGO28yb2uvCCKCLT95algM2EniE=
  app: fast-crag-17091
